#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace frmMain
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="QLLuongSP")]
	public partial class qlLuongSPDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void InserttblAccountCN(tblAccountCN instance);
    partial void UpdatetblAccountCN(tblAccountCN instance);
    partial void DeletetblAccountCN(tblAccountCN instance);
    partial void InserttblAccountNV(tblAccountNV instance);
    partial void UpdatetblAccountNV(tblAccountNV instance);
    partial void DeletetblAccountNV(tblAccountNV instance);
    partial void InserttblCongNhan(tblCongNhan instance);
    partial void UpdatetblCongNhan(tblCongNhan instance);
    partial void DeletetblCongNhan(tblCongNhan instance);
    partial void InserttblHopDong(tblHopDong instance);
    partial void UpdatetblHopDong(tblHopDong instance);
    partial void DeletetblHopDong(tblHopDong instance);
    partial void InserttblLuongCN(tblLuongCN instance);
    partial void UpdatetblLuongCN(tblLuongCN instance);
    partial void DeletetblLuongCN(tblLuongCN instance);
    partial void InserttblLuongHC(tblLuongHC instance);
    partial void UpdatetblLuongHC(tblLuongHC instance);
    partial void DeletetblLuongHC(tblLuongHC instance);
    partial void InserttblNhanVienHanhChinh(tblNhanVienHanhChinh instance);
    partial void UpdatetblNhanVienHanhChinh(tblNhanVienHanhChinh instance);
    partial void DeletetblNhanVienHanhChinh(tblNhanVienHanhChinh instance);
    partial void InserttblSanPham(tblSanPham instance);
    partial void UpdatetblSanPham(tblSanPham instance);
    partial void DeletetblSanPham(tblSanPham instance);
    #endregion
		
		public qlLuongSPDataContext() : 
				base(global::frmMain.Properties.Settings.Default.QLLuongSPConnectionString1, mappingSource)
		{
			OnCreated();
		}
		
		public qlLuongSPDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public qlLuongSPDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public qlLuongSPDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public qlLuongSPDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<tblAccountCN> tblAccountCNs
		{
			get
			{
				return this.GetTable<tblAccountCN>();
			}
		}
		
		public System.Data.Linq.Table<tblAccountNV> tblAccountNVs
		{
			get
			{
				return this.GetTable<tblAccountNV>();
			}
		}
		
		public System.Data.Linq.Table<tblCongNhan> tblCongNhans
		{
			get
			{
				return this.GetTable<tblCongNhan>();
			}
		}
		
		public System.Data.Linq.Table<tblHopDong> tblHopDongs
		{
			get
			{
				return this.GetTable<tblHopDong>();
			}
		}
		
		public System.Data.Linq.Table<tblLuongCN> tblLuongCNs
		{
			get
			{
				return this.GetTable<tblLuongCN>();
			}
		}
		
		public System.Data.Linq.Table<tblLuongHC> tblLuongHCs
		{
			get
			{
				return this.GetTable<tblLuongHC>();
			}
		}
		
		public System.Data.Linq.Table<tblNhanVienHanhChinh> tblNhanVienHanhChinhs
		{
			get
			{
				return this.GetTable<tblNhanVienHanhChinh>();
			}
		}
		
		public System.Data.Linq.Table<tblSanPham> tblSanPhams
		{
			get
			{
				return this.GetTable<tblSanPham>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.tblAccountCN")]
	public partial class tblAccountCN : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _STT;
		
		private string _IDCN;
		
		private string _PassCN;
		
		private EntityRef<tblCongNhan> _tblCongNhan;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnSTTChanging(string value);
    partial void OnSTTChanged();
    partial void OnIDCNChanging(string value);
    partial void OnIDCNChanged();
    partial void OnPassCNChanging(string value);
    partial void OnPassCNChanged();
    #endregion
		
		public tblAccountCN()
		{
			this._tblCongNhan = default(EntityRef<tblCongNhan>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_STT", DbType="NChar(2)")]
		public string STT
		{
			get
			{
				return this._STT;
			}
			set
			{
				if ((this._STT != value))
				{
					this.OnSTTChanging(value);
					this.SendPropertyChanging();
					this._STT = value;
					this.SendPropertyChanged("STT");
					this.OnSTTChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IDCN", DbType="NChar(5) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string IDCN
		{
			get
			{
				return this._IDCN;
			}
			set
			{
				if ((this._IDCN != value))
				{
					if (this._tblCongNhan.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnIDCNChanging(value);
					this.SendPropertyChanging();
					this._IDCN = value;
					this.SendPropertyChanged("IDCN");
					this.OnIDCNChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PassCN", DbType="NChar(8) NOT NULL", CanBeNull=false)]
		public string PassCN
		{
			get
			{
				return this._PassCN;
			}
			set
			{
				if ((this._PassCN != value))
				{
					this.OnPassCNChanging(value);
					this.SendPropertyChanging();
					this._PassCN = value;
					this.SendPropertyChanged("PassCN");
					this.OnPassCNChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="tblCongNhan_tblAccountCN", Storage="_tblCongNhan", ThisKey="IDCN", OtherKey="IDCN", IsForeignKey=true, DeleteOnNull=true, DeleteRule="CASCADE")]
		public tblCongNhan tblCongNhan
		{
			get
			{
				return this._tblCongNhan.Entity;
			}
			set
			{
				tblCongNhan previousValue = this._tblCongNhan.Entity;
				if (((previousValue != value) 
							|| (this._tblCongNhan.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._tblCongNhan.Entity = null;
						previousValue.tblAccountCN = null;
					}
					this._tblCongNhan.Entity = value;
					if ((value != null))
					{
						value.tblAccountCN = this;
						this._IDCN = value.IDCN;
					}
					else
					{
						this._IDCN = default(string);
					}
					this.SendPropertyChanged("tblCongNhan");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.tblAccountNV")]
	public partial class tblAccountNV : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _STT;
		
		private string _IDNV;
		
		private string _PassNV;
		
		private EntityRef<tblNhanVienHanhChinh> _tblNhanVienHanhChinh;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnSTTChanging(string value);
    partial void OnSTTChanged();
    partial void OnIDNVChanging(string value);
    partial void OnIDNVChanged();
    partial void OnPassNVChanging(string value);
    partial void OnPassNVChanged();
    #endregion
		
		public tblAccountNV()
		{
			this._tblNhanVienHanhChinh = default(EntityRef<tblNhanVienHanhChinh>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_STT", DbType="NChar(3)")]
		public string STT
		{
			get
			{
				return this._STT;
			}
			set
			{
				if ((this._STT != value))
				{
					this.OnSTTChanging(value);
					this.SendPropertyChanging();
					this._STT = value;
					this.SendPropertyChanged("STT");
					this.OnSTTChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IDNV", DbType="NChar(5) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string IDNV
		{
			get
			{
				return this._IDNV;
			}
			set
			{
				if ((this._IDNV != value))
				{
					if (this._tblNhanVienHanhChinh.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnIDNVChanging(value);
					this.SendPropertyChanging();
					this._IDNV = value;
					this.SendPropertyChanged("IDNV");
					this.OnIDNVChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PassNV", DbType="NChar(8) NOT NULL", CanBeNull=false)]
		public string PassNV
		{
			get
			{
				return this._PassNV;
			}
			set
			{
				if ((this._PassNV != value))
				{
					this.OnPassNVChanging(value);
					this.SendPropertyChanging();
					this._PassNV = value;
					this.SendPropertyChanged("PassNV");
					this.OnPassNVChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="tblNhanVienHanhChinh_tblAccountNV", Storage="_tblNhanVienHanhChinh", ThisKey="IDNV", OtherKey="IDNV", IsForeignKey=true, DeleteOnNull=true, DeleteRule="CASCADE")]
		public tblNhanVienHanhChinh tblNhanVienHanhChinh
		{
			get
			{
				return this._tblNhanVienHanhChinh.Entity;
			}
			set
			{
				tblNhanVienHanhChinh previousValue = this._tblNhanVienHanhChinh.Entity;
				if (((previousValue != value) 
							|| (this._tblNhanVienHanhChinh.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._tblNhanVienHanhChinh.Entity = null;
						previousValue.tblAccountNV = null;
					}
					this._tblNhanVienHanhChinh.Entity = value;
					if ((value != null))
					{
						value.tblAccountNV = this;
						this._IDNV = value.IDNV;
					}
					else
					{
						this._IDNV = default(string);
					}
					this.SendPropertyChanged("tblNhanVienHanhChinh");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.tblCongNhan")]
	public partial class tblCongNhan : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _IDCN;
		
		private string _HoTen;
		
		private string _GioiTinh;
		
		private System.DateTime _NgaySinh;
		
		private System.DateTime _NgayBatDau;
		
		private string _CongDoan;
		
		private decimal _HeSoLuongCD;
		
		private string _IDSanPham;
		
		private EntityRef<tblAccountCN> _tblAccountCN;
		
		private EntitySet<tblLuongCN> _tblLuongCNs;
		
		private EntityRef<tblSanPham> _tblSanPham;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIDCNChanging(string value);
    partial void OnIDCNChanged();
    partial void OnHoTenChanging(string value);
    partial void OnHoTenChanged();
    partial void OnGioiTinhChanging(string value);
    partial void OnGioiTinhChanged();
    partial void OnNgaySinhChanging(System.DateTime value);
    partial void OnNgaySinhChanged();
    partial void OnNgayBatDauChanging(System.DateTime value);
    partial void OnNgayBatDauChanged();
    partial void OnCongDoanChanging(string value);
    partial void OnCongDoanChanged();
    partial void OnHeSoLuongCDChanging(decimal value);
    partial void OnHeSoLuongCDChanged();
    partial void OnIDSanPhamChanging(string value);
    partial void OnIDSanPhamChanged();
    #endregion
		
		public tblCongNhan()
		{
			this._tblAccountCN = default(EntityRef<tblAccountCN>);
			this._tblLuongCNs = new EntitySet<tblLuongCN>(new Action<tblLuongCN>(this.attach_tblLuongCNs), new Action<tblLuongCN>(this.detach_tblLuongCNs));
			this._tblSanPham = default(EntityRef<tblSanPham>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IDCN", DbType="NChar(5) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string IDCN
		{
			get
			{
				return this._IDCN;
			}
			set
			{
				if ((this._IDCN != value))
				{
					this.OnIDCNChanging(value);
					this.SendPropertyChanging();
					this._IDCN = value;
					this.SendPropertyChanged("IDCN");
					this.OnIDCNChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_HoTen", DbType="NChar(30) NOT NULL", CanBeNull=false)]
		public string HoTen
		{
			get
			{
				return this._HoTen;
			}
			set
			{
				if ((this._HoTen != value))
				{
					this.OnHoTenChanging(value);
					this.SendPropertyChanging();
					this._HoTen = value;
					this.SendPropertyChanged("HoTen");
					this.OnHoTenChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_GioiTinh", DbType="NChar(10) NOT NULL", CanBeNull=false)]
		public string GioiTinh
		{
			get
			{
				return this._GioiTinh;
			}
			set
			{
				if ((this._GioiTinh != value))
				{
					this.OnGioiTinhChanging(value);
					this.SendPropertyChanging();
					this._GioiTinh = value;
					this.SendPropertyChanged("GioiTinh");
					this.OnGioiTinhChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NgaySinh", DbType="Date NOT NULL")]
		public System.DateTime NgaySinh
		{
			get
			{
				return this._NgaySinh;
			}
			set
			{
				if ((this._NgaySinh != value))
				{
					this.OnNgaySinhChanging(value);
					this.SendPropertyChanging();
					this._NgaySinh = value;
					this.SendPropertyChanged("NgaySinh");
					this.OnNgaySinhChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NgayBatDau", DbType="Date NOT NULL")]
		public System.DateTime NgayBatDau
		{
			get
			{
				return this._NgayBatDau;
			}
			set
			{
				if ((this._NgayBatDau != value))
				{
					this.OnNgayBatDauChanging(value);
					this.SendPropertyChanging();
					this._NgayBatDau = value;
					this.SendPropertyChanged("NgayBatDau");
					this.OnNgayBatDauChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CongDoan", DbType="NChar(10) NOT NULL", CanBeNull=false)]
		public string CongDoan
		{
			get
			{
				return this._CongDoan;
			}
			set
			{
				if ((this._CongDoan != value))
				{
					this.OnCongDoanChanging(value);
					this.SendPropertyChanging();
					this._CongDoan = value;
					this.SendPropertyChanged("CongDoan");
					this.OnCongDoanChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_HeSoLuongCD", DbType="Decimal(18,0) NOT NULL")]
		public decimal HeSoLuongCD
		{
			get
			{
				return this._HeSoLuongCD;
			}
			set
			{
				if ((this._HeSoLuongCD != value))
				{
					this.OnHeSoLuongCDChanging(value);
					this.SendPropertyChanging();
					this._HeSoLuongCD = value;
					this.SendPropertyChanged("HeSoLuongCD");
					this.OnHeSoLuongCDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IDSanPham", DbType="NChar(5) NOT NULL", CanBeNull=false)]
		public string IDSanPham
		{
			get
			{
				return this._IDSanPham;
			}
			set
			{
				if ((this._IDSanPham != value))
				{
					if (this._tblSanPham.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnIDSanPhamChanging(value);
					this.SendPropertyChanging();
					this._IDSanPham = value;
					this.SendPropertyChanged("IDSanPham");
					this.OnIDSanPhamChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="tblCongNhan_tblAccountCN", Storage="_tblAccountCN", ThisKey="IDCN", OtherKey="IDCN", IsUnique=true, IsForeignKey=false)]
		public tblAccountCN tblAccountCN
		{
			get
			{
				return this._tblAccountCN.Entity;
			}
			set
			{
				tblAccountCN previousValue = this._tblAccountCN.Entity;
				if (((previousValue != value) 
							|| (this._tblAccountCN.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._tblAccountCN.Entity = null;
						previousValue.tblCongNhan = null;
					}
					this._tblAccountCN.Entity = value;
					if ((value != null))
					{
						value.tblCongNhan = this;
					}
					this.SendPropertyChanged("tblAccountCN");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="tblCongNhan_tblLuongCN", Storage="_tblLuongCNs", ThisKey="IDCN", OtherKey="IDCN")]
		public EntitySet<tblLuongCN> tblLuongCNs
		{
			get
			{
				return this._tblLuongCNs;
			}
			set
			{
				this._tblLuongCNs.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="tblSanPham_tblCongNhan", Storage="_tblSanPham", ThisKey="IDSanPham", OtherKey="IDSanPham", IsForeignKey=true, DeleteOnNull=true, DeleteRule="CASCADE")]
		public tblSanPham tblSanPham
		{
			get
			{
				return this._tblSanPham.Entity;
			}
			set
			{
				tblSanPham previousValue = this._tblSanPham.Entity;
				if (((previousValue != value) 
							|| (this._tblSanPham.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._tblSanPham.Entity = null;
						previousValue.tblCongNhans.Remove(this);
					}
					this._tblSanPham.Entity = value;
					if ((value != null))
					{
						value.tblCongNhans.Add(this);
						this._IDSanPham = value.IDSanPham;
					}
					else
					{
						this._IDSanPham = default(string);
					}
					this.SendPropertyChanged("tblSanPham");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_tblLuongCNs(tblLuongCN entity)
		{
			this.SendPropertyChanging();
			entity.tblCongNhan = this;
		}
		
		private void detach_tblLuongCNs(tblLuongCN entity)
		{
			this.SendPropertyChanging();
			entity.tblCongNhan = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.tblHopDong")]
	public partial class tblHopDong : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _IDHopDong;
		
		private string _Ten;
		
		private System.DateTime _NgayBatDau;
		
		private System.DateTime _NgayKetThuc;
		
		private EntitySet<tblNhanVienHanhChinh> _tblNhanVienHanhChinhs;
		
		private EntitySet<tblSanPham> _tblSanPhams;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIDHopDongChanging(string value);
    partial void OnIDHopDongChanged();
    partial void OnTenChanging(string value);
    partial void OnTenChanged();
    partial void OnNgayBatDauChanging(System.DateTime value);
    partial void OnNgayBatDauChanged();
    partial void OnNgayKetThucChanging(System.DateTime value);
    partial void OnNgayKetThucChanged();
    #endregion
		
		public tblHopDong()
		{
			this._tblNhanVienHanhChinhs = new EntitySet<tblNhanVienHanhChinh>(new Action<tblNhanVienHanhChinh>(this.attach_tblNhanVienHanhChinhs), new Action<tblNhanVienHanhChinh>(this.detach_tblNhanVienHanhChinhs));
			this._tblSanPhams = new EntitySet<tblSanPham>(new Action<tblSanPham>(this.attach_tblSanPhams), new Action<tblSanPham>(this.detach_tblSanPhams));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IDHopDong", DbType="NChar(5) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string IDHopDong
		{
			get
			{
				return this._IDHopDong;
			}
			set
			{
				if ((this._IDHopDong != value))
				{
					this.OnIDHopDongChanging(value);
					this.SendPropertyChanging();
					this._IDHopDong = value;
					this.SendPropertyChanged("IDHopDong");
					this.OnIDHopDongChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Ten", DbType="NChar(50) NOT NULL", CanBeNull=false)]
		public string Ten
		{
			get
			{
				return this._Ten;
			}
			set
			{
				if ((this._Ten != value))
				{
					this.OnTenChanging(value);
					this.SendPropertyChanging();
					this._Ten = value;
					this.SendPropertyChanged("Ten");
					this.OnTenChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NgayBatDau", DbType="Date NOT NULL")]
		public System.DateTime NgayBatDau
		{
			get
			{
				return this._NgayBatDau;
			}
			set
			{
				if ((this._NgayBatDau != value))
				{
					this.OnNgayBatDauChanging(value);
					this.SendPropertyChanging();
					this._NgayBatDau = value;
					this.SendPropertyChanged("NgayBatDau");
					this.OnNgayBatDauChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NgayKetThuc", DbType="Date NOT NULL")]
		public System.DateTime NgayKetThuc
		{
			get
			{
				return this._NgayKetThuc;
			}
			set
			{
				if ((this._NgayKetThuc != value))
				{
					this.OnNgayKetThucChanging(value);
					this.SendPropertyChanging();
					this._NgayKetThuc = value;
					this.SendPropertyChanged("NgayKetThuc");
					this.OnNgayKetThucChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="tblHopDong_tblNhanVienHanhChinh", Storage="_tblNhanVienHanhChinhs", ThisKey="IDHopDong", OtherKey="IDHopDong")]
		public EntitySet<tblNhanVienHanhChinh> tblNhanVienHanhChinhs
		{
			get
			{
				return this._tblNhanVienHanhChinhs;
			}
			set
			{
				this._tblNhanVienHanhChinhs.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="tblHopDong_tblSanPham", Storage="_tblSanPhams", ThisKey="IDHopDong", OtherKey="IDHopDong")]
		public EntitySet<tblSanPham> tblSanPhams
		{
			get
			{
				return this._tblSanPhams;
			}
			set
			{
				this._tblSanPhams.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_tblNhanVienHanhChinhs(tblNhanVienHanhChinh entity)
		{
			this.SendPropertyChanging();
			entity.tblHopDong = this;
		}
		
		private void detach_tblNhanVienHanhChinhs(tblNhanVienHanhChinh entity)
		{
			this.SendPropertyChanging();
			entity.tblHopDong = null;
		}
		
		private void attach_tblSanPhams(tblSanPham entity)
		{
			this.SendPropertyChanging();
			entity.tblHopDong = this;
		}
		
		private void detach_tblSanPhams(tblSanPham entity)
		{
			this.SendPropertyChanging();
			entity.tblHopDong = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.tblLuongCN")]
	public partial class tblLuongCN : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _STT;
		
		private double _HeSoCa;
		
		private int _SoLuong;
		
		private string _IDCN;
		
		private EntityRef<tblCongNhan> _tblCongNhan;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnSTTChanging(string value);
    partial void OnSTTChanged();
    partial void OnHeSoCaChanging(double value);
    partial void OnHeSoCaChanged();
    partial void OnSoLuongChanging(int value);
    partial void OnSoLuongChanged();
    partial void OnIDCNChanging(string value);
    partial void OnIDCNChanged();
    #endregion
		
		public tblLuongCN()
		{
			this._tblCongNhan = default(EntityRef<tblCongNhan>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_STT", DbType="NChar(5) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string STT
		{
			get
			{
				return this._STT;
			}
			set
			{
				if ((this._STT != value))
				{
					this.OnSTTChanging(value);
					this.SendPropertyChanging();
					this._STT = value;
					this.SendPropertyChanged("STT");
					this.OnSTTChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_HeSoCa", DbType="Float NOT NULL")]
		public double HeSoCa
		{
			get
			{
				return this._HeSoCa;
			}
			set
			{
				if ((this._HeSoCa != value))
				{
					this.OnHeSoCaChanging(value);
					this.SendPropertyChanging();
					this._HeSoCa = value;
					this.SendPropertyChanged("HeSoCa");
					this.OnHeSoCaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SoLuong", DbType="Int NOT NULL")]
		public int SoLuong
		{
			get
			{
				return this._SoLuong;
			}
			set
			{
				if ((this._SoLuong != value))
				{
					this.OnSoLuongChanging(value);
					this.SendPropertyChanging();
					this._SoLuong = value;
					this.SendPropertyChanged("SoLuong");
					this.OnSoLuongChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IDCN", DbType="NChar(5) NOT NULL", CanBeNull=false)]
		public string IDCN
		{
			get
			{
				return this._IDCN;
			}
			set
			{
				if ((this._IDCN != value))
				{
					if (this._tblCongNhan.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnIDCNChanging(value);
					this.SendPropertyChanging();
					this._IDCN = value;
					this.SendPropertyChanged("IDCN");
					this.OnIDCNChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="tblCongNhan_tblLuongCN", Storage="_tblCongNhan", ThisKey="IDCN", OtherKey="IDCN", IsForeignKey=true, DeleteOnNull=true, DeleteRule="CASCADE")]
		public tblCongNhan tblCongNhan
		{
			get
			{
				return this._tblCongNhan.Entity;
			}
			set
			{
				tblCongNhan previousValue = this._tblCongNhan.Entity;
				if (((previousValue != value) 
							|| (this._tblCongNhan.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._tblCongNhan.Entity = null;
						previousValue.tblLuongCNs.Remove(this);
					}
					this._tblCongNhan.Entity = value;
					if ((value != null))
					{
						value.tblLuongCNs.Add(this);
						this._IDCN = value.IDCN;
					}
					else
					{
						this._IDCN = default(string);
					}
					this.SendPropertyChanged("tblCongNhan");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.tblLuongHC")]
	public partial class tblLuongHC : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _STT;
		
		private System.Nullable<decimal> _SoNgayLam;
		
		private System.Nullable<decimal> _SoGioNgoai;
		
		private string _IDNV;
		
		private EntityRef<tblNhanVienHanhChinh> _tblNhanVienHanhChinh;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnSTTChanging(string value);
    partial void OnSTTChanged();
    partial void OnSoNgayLamChanging(System.Nullable<decimal> value);
    partial void OnSoNgayLamChanged();
    partial void OnSoGioNgoaiChanging(System.Nullable<decimal> value);
    partial void OnSoGioNgoaiChanged();
    partial void OnIDNVChanging(string value);
    partial void OnIDNVChanged();
    #endregion
		
		public tblLuongHC()
		{
			this._tblNhanVienHanhChinh = default(EntityRef<tblNhanVienHanhChinh>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_STT", DbType="NChar(3) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string STT
		{
			get
			{
				return this._STT;
			}
			set
			{
				if ((this._STT != value))
				{
					this.OnSTTChanging(value);
					this.SendPropertyChanging();
					this._STT = value;
					this.SendPropertyChanged("STT");
					this.OnSTTChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SoNgayLam", DbType="Decimal(18,0)")]
		public System.Nullable<decimal> SoNgayLam
		{
			get
			{
				return this._SoNgayLam;
			}
			set
			{
				if ((this._SoNgayLam != value))
				{
					this.OnSoNgayLamChanging(value);
					this.SendPropertyChanging();
					this._SoNgayLam = value;
					this.SendPropertyChanged("SoNgayLam");
					this.OnSoNgayLamChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SoGioNgoai", DbType="Decimal(18,0)")]
		public System.Nullable<decimal> SoGioNgoai
		{
			get
			{
				return this._SoGioNgoai;
			}
			set
			{
				if ((this._SoGioNgoai != value))
				{
					this.OnSoGioNgoaiChanging(value);
					this.SendPropertyChanging();
					this._SoGioNgoai = value;
					this.SendPropertyChanged("SoGioNgoai");
					this.OnSoGioNgoaiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IDNV", DbType="NChar(5) NOT NULL", CanBeNull=false)]
		public string IDNV
		{
			get
			{
				return this._IDNV;
			}
			set
			{
				if ((this._IDNV != value))
				{
					if (this._tblNhanVienHanhChinh.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnIDNVChanging(value);
					this.SendPropertyChanging();
					this._IDNV = value;
					this.SendPropertyChanged("IDNV");
					this.OnIDNVChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="tblNhanVienHanhChinh_tblLuongHC", Storage="_tblNhanVienHanhChinh", ThisKey="IDNV", OtherKey="IDNV", IsForeignKey=true, DeleteOnNull=true, DeleteRule="CASCADE")]
		public tblNhanVienHanhChinh tblNhanVienHanhChinh
		{
			get
			{
				return this._tblNhanVienHanhChinh.Entity;
			}
			set
			{
				tblNhanVienHanhChinh previousValue = this._tblNhanVienHanhChinh.Entity;
				if (((previousValue != value) 
							|| (this._tblNhanVienHanhChinh.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._tblNhanVienHanhChinh.Entity = null;
						previousValue.tblLuongHCs.Remove(this);
					}
					this._tblNhanVienHanhChinh.Entity = value;
					if ((value != null))
					{
						value.tblLuongHCs.Add(this);
						this._IDNV = value.IDNV;
					}
					else
					{
						this._IDNV = default(string);
					}
					this.SendPropertyChanged("tblNhanVienHanhChinh");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.tblNhanVienHanhChinh")]
	public partial class tblNhanVienHanhChinh : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _IDNV;
		
		private string _HoTen;
		
		private string _GioiTinh;
		
		private System.DateTime _NgaySinh;
		
		private System.DateTime _NgayBatDau;
		
		private decimal _HeSoLuong;
		
		private decimal _PhuCap;
		
		private string _IDHopDong;
		
		private EntityRef<tblAccountNV> _tblAccountNV;
		
		private EntitySet<tblLuongHC> _tblLuongHCs;
		
		private EntityRef<tblHopDong> _tblHopDong;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIDNVChanging(string value);
    partial void OnIDNVChanged();
    partial void OnHoTenChanging(string value);
    partial void OnHoTenChanged();
    partial void OnGioiTinhChanging(string value);
    partial void OnGioiTinhChanged();
    partial void OnNgaySinhChanging(System.DateTime value);
    partial void OnNgaySinhChanged();
    partial void OnNgayBatDauChanging(System.DateTime value);
    partial void OnNgayBatDauChanged();
    partial void OnHeSoLuongChanging(decimal value);
    partial void OnHeSoLuongChanged();
    partial void OnPhuCapChanging(decimal value);
    partial void OnPhuCapChanged();
    partial void OnIDHopDongChanging(string value);
    partial void OnIDHopDongChanged();
    #endregion
		
		public tblNhanVienHanhChinh()
		{
			this._tblAccountNV = default(EntityRef<tblAccountNV>);
			this._tblLuongHCs = new EntitySet<tblLuongHC>(new Action<tblLuongHC>(this.attach_tblLuongHCs), new Action<tblLuongHC>(this.detach_tblLuongHCs));
			this._tblHopDong = default(EntityRef<tblHopDong>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IDNV", DbType="NChar(5) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string IDNV
		{
			get
			{
				return this._IDNV;
			}
			set
			{
				if ((this._IDNV != value))
				{
					this.OnIDNVChanging(value);
					this.SendPropertyChanging();
					this._IDNV = value;
					this.SendPropertyChanged("IDNV");
					this.OnIDNVChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_HoTen", DbType="NChar(30) NOT NULL", CanBeNull=false)]
		public string HoTen
		{
			get
			{
				return this._HoTen;
			}
			set
			{
				if ((this._HoTen != value))
				{
					this.OnHoTenChanging(value);
					this.SendPropertyChanging();
					this._HoTen = value;
					this.SendPropertyChanged("HoTen");
					this.OnHoTenChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_GioiTinh", DbType="NChar(3) NOT NULL", CanBeNull=false)]
		public string GioiTinh
		{
			get
			{
				return this._GioiTinh;
			}
			set
			{
				if ((this._GioiTinh != value))
				{
					this.OnGioiTinhChanging(value);
					this.SendPropertyChanging();
					this._GioiTinh = value;
					this.SendPropertyChanged("GioiTinh");
					this.OnGioiTinhChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NgaySinh", DbType="Date NOT NULL")]
		public System.DateTime NgaySinh
		{
			get
			{
				return this._NgaySinh;
			}
			set
			{
				if ((this._NgaySinh != value))
				{
					this.OnNgaySinhChanging(value);
					this.SendPropertyChanging();
					this._NgaySinh = value;
					this.SendPropertyChanged("NgaySinh");
					this.OnNgaySinhChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NgayBatDau", DbType="Date NOT NULL")]
		public System.DateTime NgayBatDau
		{
			get
			{
				return this._NgayBatDau;
			}
			set
			{
				if ((this._NgayBatDau != value))
				{
					this.OnNgayBatDauChanging(value);
					this.SendPropertyChanging();
					this._NgayBatDau = value;
					this.SendPropertyChanged("NgayBatDau");
					this.OnNgayBatDauChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_HeSoLuong", DbType="Decimal(18,0) NOT NULL")]
		public decimal HeSoLuong
		{
			get
			{
				return this._HeSoLuong;
			}
			set
			{
				if ((this._HeSoLuong != value))
				{
					this.OnHeSoLuongChanging(value);
					this.SendPropertyChanging();
					this._HeSoLuong = value;
					this.SendPropertyChanged("HeSoLuong");
					this.OnHeSoLuongChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PhuCap", DbType="Decimal(18,0) NOT NULL")]
		public decimal PhuCap
		{
			get
			{
				return this._PhuCap;
			}
			set
			{
				if ((this._PhuCap != value))
				{
					this.OnPhuCapChanging(value);
					this.SendPropertyChanging();
					this._PhuCap = value;
					this.SendPropertyChanged("PhuCap");
					this.OnPhuCapChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IDHopDong", DbType="NChar(5) NOT NULL", CanBeNull=false)]
		public string IDHopDong
		{
			get
			{
				return this._IDHopDong;
			}
			set
			{
				if ((this._IDHopDong != value))
				{
					if (this._tblHopDong.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnIDHopDongChanging(value);
					this.SendPropertyChanging();
					this._IDHopDong = value;
					this.SendPropertyChanged("IDHopDong");
					this.OnIDHopDongChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="tblNhanVienHanhChinh_tblAccountNV", Storage="_tblAccountNV", ThisKey="IDNV", OtherKey="IDNV", IsUnique=true, IsForeignKey=false)]
		public tblAccountNV tblAccountNV
		{
			get
			{
				return this._tblAccountNV.Entity;
			}
			set
			{
				tblAccountNV previousValue = this._tblAccountNV.Entity;
				if (((previousValue != value) 
							|| (this._tblAccountNV.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._tblAccountNV.Entity = null;
						previousValue.tblNhanVienHanhChinh = null;
					}
					this._tblAccountNV.Entity = value;
					if ((value != null))
					{
						value.tblNhanVienHanhChinh = this;
					}
					this.SendPropertyChanged("tblAccountNV");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="tblNhanVienHanhChinh_tblLuongHC", Storage="_tblLuongHCs", ThisKey="IDNV", OtherKey="IDNV")]
		public EntitySet<tblLuongHC> tblLuongHCs
		{
			get
			{
				return this._tblLuongHCs;
			}
			set
			{
				this._tblLuongHCs.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="tblHopDong_tblNhanVienHanhChinh", Storage="_tblHopDong", ThisKey="IDHopDong", OtherKey="IDHopDong", IsForeignKey=true, DeleteOnNull=true, DeleteRule="CASCADE")]
		public tblHopDong tblHopDong
		{
			get
			{
				return this._tblHopDong.Entity;
			}
			set
			{
				tblHopDong previousValue = this._tblHopDong.Entity;
				if (((previousValue != value) 
							|| (this._tblHopDong.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._tblHopDong.Entity = null;
						previousValue.tblNhanVienHanhChinhs.Remove(this);
					}
					this._tblHopDong.Entity = value;
					if ((value != null))
					{
						value.tblNhanVienHanhChinhs.Add(this);
						this._IDHopDong = value.IDHopDong;
					}
					else
					{
						this._IDHopDong = default(string);
					}
					this.SendPropertyChanged("tblHopDong");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_tblLuongHCs(tblLuongHC entity)
		{
			this.SendPropertyChanging();
			entity.tblNhanVienHanhChinh = this;
		}
		
		private void detach_tblLuongHCs(tblLuongHC entity)
		{
			this.SendPropertyChanging();
			entity.tblNhanVienHanhChinh = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.tblSanPham")]
	public partial class tblSanPham : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _IDSanPham;
		
		private string _TenSanPham;
		
		private string _DonViTinh;
		
		private string _IDHopDong;
		
		private EntitySet<tblCongNhan> _tblCongNhans;
		
		private EntityRef<tblHopDong> _tblHopDong;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIDSanPhamChanging(string value);
    partial void OnIDSanPhamChanged();
    partial void OnTenSanPhamChanging(string value);
    partial void OnTenSanPhamChanged();
    partial void OnDonViTinhChanging(string value);
    partial void OnDonViTinhChanged();
    partial void OnIDHopDongChanging(string value);
    partial void OnIDHopDongChanged();
    #endregion
		
		public tblSanPham()
		{
			this._tblCongNhans = new EntitySet<tblCongNhan>(new Action<tblCongNhan>(this.attach_tblCongNhans), new Action<tblCongNhan>(this.detach_tblCongNhans));
			this._tblHopDong = default(EntityRef<tblHopDong>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IDSanPham", DbType="NChar(5) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string IDSanPham
		{
			get
			{
				return this._IDSanPham;
			}
			set
			{
				if ((this._IDSanPham != value))
				{
					this.OnIDSanPhamChanging(value);
					this.SendPropertyChanging();
					this._IDSanPham = value;
					this.SendPropertyChanged("IDSanPham");
					this.OnIDSanPhamChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TenSanPham", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string TenSanPham
		{
			get
			{
				return this._TenSanPham;
			}
			set
			{
				if ((this._TenSanPham != value))
				{
					this.OnTenSanPhamChanging(value);
					this.SendPropertyChanging();
					this._TenSanPham = value;
					this.SendPropertyChanged("TenSanPham");
					this.OnTenSanPhamChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DonViTinh", DbType="NChar(20) NOT NULL", CanBeNull=false)]
		public string DonViTinh
		{
			get
			{
				return this._DonViTinh;
			}
			set
			{
				if ((this._DonViTinh != value))
				{
					this.OnDonViTinhChanging(value);
					this.SendPropertyChanging();
					this._DonViTinh = value;
					this.SendPropertyChanged("DonViTinh");
					this.OnDonViTinhChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IDHopDong", DbType="NChar(5) NOT NULL", CanBeNull=false)]
		public string IDHopDong
		{
			get
			{
				return this._IDHopDong;
			}
			set
			{
				if ((this._IDHopDong != value))
				{
					if (this._tblHopDong.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnIDHopDongChanging(value);
					this.SendPropertyChanging();
					this._IDHopDong = value;
					this.SendPropertyChanged("IDHopDong");
					this.OnIDHopDongChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="tblSanPham_tblCongNhan", Storage="_tblCongNhans", ThisKey="IDSanPham", OtherKey="IDSanPham")]
		public EntitySet<tblCongNhan> tblCongNhans
		{
			get
			{
				return this._tblCongNhans;
			}
			set
			{
				this._tblCongNhans.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="tblHopDong_tblSanPham", Storage="_tblHopDong", ThisKey="IDHopDong", OtherKey="IDHopDong", IsForeignKey=true, DeleteOnNull=true, DeleteRule="CASCADE")]
		public tblHopDong tblHopDong
		{
			get
			{
				return this._tblHopDong.Entity;
			}
			set
			{
				tblHopDong previousValue = this._tblHopDong.Entity;
				if (((previousValue != value) 
							|| (this._tblHopDong.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._tblHopDong.Entity = null;
						previousValue.tblSanPhams.Remove(this);
					}
					this._tblHopDong.Entity = value;
					if ((value != null))
					{
						value.tblSanPhams.Add(this);
						this._IDHopDong = value.IDHopDong;
					}
					else
					{
						this._IDHopDong = default(string);
					}
					this.SendPropertyChanged("tblHopDong");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_tblCongNhans(tblCongNhan entity)
		{
			this.SendPropertyChanging();
			entity.tblSanPham = this;
		}
		
		private void detach_tblCongNhans(tblCongNhan entity)
		{
			this.SendPropertyChanging();
			entity.tblSanPham = null;
		}
	}
}
#pragma warning restore 1591
